In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])

In [3]:
b = np.arange(4)

In [4]:
print(a,b)

[10 20 30 40] [0 1 2 3]


In [5]:
c = a + b  # 简单计算（加减乘除）

In [6]:
print(c)

[10 21 32 43]


In [7]:
d = 10*np.sin(a)  # 函数计算(sin, cos等)

In [8]:
print(d)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [9]:
print(b<3)

[ True  True  True False]


In [10]:
m = np.array([[1,1],
              [0,1]])

In [11]:
n = np.arange(4).reshape((2,2))

In [12]:
print(m)

[[1 1]
 [0 1]]


In [13]:
print(n)

[[0 1]
 [2 3]]


In [14]:
p = m * n  # 矩阵对应位置元素相乘

In [15]:
print(p)

[[0 1]
 [0 3]]


In [16]:
p_dot = np.dot(m,n)  # 矩阵乘法

In [17]:
print(p_dot)

[[2 4]
 [2 3]]


In [18]:
p_dot_2 = m.dot(n)  # 矩阵乘法

In [19]:
print(p_dot_2)

[[2 4]
 [2 3]]


In [20]:
h = np.random.random((2,4))  # 随机矩阵

In [21]:
print(h)

[[0.54647191 0.20997796 0.47363169 0.09308206]
 [0.25728458 0.31800801 0.29876242 0.5623188 ]]


In [24]:
print(np.min(h, axis=1))  # 每一行中的最小值

[0.09308206 0.25728458]


In [25]:
print(np.sum(h, axis=0))  # 每一列求和

[0.80375649 0.52798597 0.77239411 0.65540086]
