In [1]:
import numpy as np

In [2]:
A = np.arange(2,14).reshape((3,4))

In [3]:
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [4]:
print(np.argmin(A))  # 最小值的索引

0


In [5]:
print(np.argmax(A))  # 最大值的索引

11


In [6]:
print(np.mean(A))  # 计算平均值,或者A.mean()

7.5


In [7]:
print(np.median(A))  # 计算中位数

7.5


In [8]:
# 其它函数:累加函数cumsum;累差函数diff;排序函数sort;矩阵转置transpose;

In [9]:
print(A.T.dot(A))  # 例子

[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]


In [10]:
# clip函数：这个函数的格式是clip(Array,Array_min,Array_max)，顾名思义，Array指的是将要被执行用的矩阵，而后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值

In [14]:
print(np.clip(A,5,9))

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
