In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)

In [3]:
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
print(A[3])  # 一维数组索引

6


In [5]:
B = np.arange(3,15).reshape((3,4))

In [6]:
print(B)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [7]:
print(B[1][1])  # 矩阵索引，或者B[1,1]

8


In [8]:
print(B[0:2,1])  # 第一列的前两个数字

[4 8]


In [9]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [10]:
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [11]:
print(B.flatten())  # 扁平化

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
for item in B.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
