In [1]:
import numpy as np

In [2]:
A = np.array([1,1,1])

In [3]:
B = np.array([2,2,2])

In [4]:
print(np.vstack((A,B)))  # vertical stack

[[1 1 1]
 [2 2 2]]


In [5]:
print(np.stack([A, B], axis=0))

[[1 1 1]
 [2 2 2]]


In [6]:
print(np.hstack((A,B)))  # horizontal stack

[1 1 1 2 2 2]


In [7]:
print(np.stack([A, B], axis=1))

[[1 2]
 [1 2]
 [1 2]]


In [8]:
C = np.array([1,1,1])[:, np.newaxis]  # 增加维度(列),如果增加行则[np.newaxis, :]

In [9]:
print(A.shape)

(3,)


In [10]:
print(C.shape)

(3, 1)


In [11]:
D = np.array([2,2,2])[:, np.newaxis]

In [12]:
print(np.hstack((C,D)))

[[1 2]
 [1 2]
 [1 2]]


In [13]:
E = np.concatenate((C,D,D,C), axis=1)  # 横向合并

In [14]:
print(E)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
